### ISSUE TITLE
Перестали скрываться блоки при первоначальной загрузке страницы

### ISSUE THREAD

**Issue by Goncharenok** [ppskmg/TildaTabs#1]
Милчеловек @ppskmg , все работало на 100%, шикарное решение, написанное для тупых, как я.

Но сейчас, спустя год, зашла на сайт, а при первичной загрузке (пока не нажать на одну из ссылок блока "Области практики" открыты все блоки(( Буду рада совету, что не так-то(

Код скрипта ниже. Ссылка на сайт [тут](https://forensicalliance.ru/).
[fa.txt](https://github.com/ppskmg/TildaTabs/files/8903145/fa.txt)

**Comment by ppskmg** [comment]
> Милчеловек @ppskmg , все работало на 100%, шикарное решение, написанное для тупых, как я.
> 
> Но сейчас, спустя год, зашла на сайт, а при первичной загрузке (пока не нажать на одну из ссылок блока "Области практики" открыты все блоки(( Буду рада совету, что не так-то(
> 
> Код скрипта ниже. Ссылка на сайт [тут](https://forensicalliance.ru/). [fa.txt](https://github.com/ppskmg/TildaTabs/files/8903145/fa.txt)



`blocksId = getBlocksId(allBlocks) // получаем массив с id блоков`
 
замените на
`let blocksId = getBlocksId(allBlocks) // получаем массив с id блоков`
не объявлена переменная


Дополнительно на сайте есть ошибка, 
Uncaught ReferenceError: Stats is not defined
в коде particlesJS(....
